### ISSUE TITLE
[Bug]: Picker - Filter A - Z failed

### ISSUE THREAD

**Issue by YaniceJ** [LangaraVoyagers/project-2#112]
### Description

In the Picker Page, when I try to filter from A to Z, but it failed. The pickers name shows "P" before "A". 

### Reproduction steps

```bash
1. Go to 'Picker' Page
2. Click on 'Filter' button
3. Scroll down and choose 'From A - Z'
4. See error
```

### Screenshots / Screen Recordings

Paste, drag and drop, or click option below to add your files here.
![Picker - Filter A - Z failed](https://github.com/LangaraVoyagers/project-2/assets/161170980/2b74ffb2-e49f-48d9-b75e-9a8d0b842c41)

### Browsers

Chrome

### OS

Mac

**Comment by ReinhardtBotha** [comment]
This Picker has a bunch of spaces before its name, thats why its doing this. But the sort works.
![image](https://github.com/LangaraVoyagers/project-2/assets/89278135/a3da42b6-aef6-4a78-9660-c3f9b859fa17)
