### ISSUE TITLE
Dashboard - Spacing issues in payroll cards

### ISSUE THREAD

**Issue by poojachauhan001** [LangaraVoyagers/project-2#131]
### Description

The spacing between elements doesn’t match the mockup for payroll card on dashboard

### Reproduction steps

```bash
1. login
2. scroll till bottom on dashboard
```

### Screenshots / Screen Recordings

<img width="1135" alt="spacing bug" src="https://github.com/LangaraVoyagers/project-2/assets/144421139/257e5ad8-7f01-491a-b159-4e1f8e643e5c">

Figma:
<img width="819" alt="spacing bug - figma fix" src="https://github.com/LangaraVoyagers/project-2/assets/144421139/21bc4474-6e51-46c6-ac45-e486933fd246">

### Browsers

Chrome

### OS

Mac

**Comment by ReinhardtBotha** [comment]
already fixed
