### ISSUE TITLE
harvest Season - Wrong highlight color used

### ISSUE THREAD

**Issue by poojachauhan001** [LangaraVoyagers/project-2#144]
### Description

For highlighting the name of the new season that has been created, the color being used is incorrect. Please fix the colour as used in the mockup

### Reproduction steps

```bash
1. go to harvest season page
2. create a new season
3. check the confirmation in the drawer
```

### Screenshots / Screen Recordings

<img width="544" alt="col" src="https://github.com/LangaraVoyagers/project-2/assets/144421139/0437c023-e0cc-48e9-b516-cf172920c893">

figma:
<img width="690" alt="col-fig" src="https://github.com/LangaraVoyagers/project-2/assets/144421139/a005a6e4-4f18-408c-ad99-17574e095ada">

### Browsers

Chrome

### OS

Mac

**Comment by whamester** [comment]
<img width="497" alt="Screenshot 2024-04-02 at 6 01 07 PM" src="https://github.com/LangaraVoyagers/project-2/assets/57273227/d87b2076-8bc9-4ed6-a25a-838e52ea57a9">
