### ISSUE TITLE
[Bug]: Harvest Log - Cannot create correction entry

### ISSUE THREAD

**Issue by whamester** [LangaraVoyagers/project-2#168]
### Description

Saving correction entry displays an error

### Reproduction steps

```bash
1. Go to https://plowterra.com/harvest-logs
2. Click on any harvest log entry
3. Create a new correction entry
4. See error
```

### Screenshots / Screen Recordings

https://github.com/LangaraVoyagers/project-2/assets/57273227/e29e0354-8727-42eb-9a9d-54550a6aded6

### Browsers

Chrome

### OS

Mac

**Comment by ReinhardtBotha** [comment]
duplicate: https://github.com/LangaraVoyagers/project-2/issues/157
