### ISSUE TITLE
[Bug]: Picker - Add Picker - Drawer Button Position

### ISSUE THREAD

**Issue by Lizetteffkb** [LangaraVoyagers/project-2#40]
### Description

[Cancel] and [Confirm] should always stick to the bottom and please pay attention to the gap. Please check the design spec for the drawer in this figma file 
QA Notes - Picker Management [https://www.figma.com/file/ng4BaOBGYeSWjaGXYmOOOR/QA-Notes?type=design&node-id=13%3A2&mode=design&t=CDzXGv2PAQ2VTcEN-1](url)

### Reproduction steps

```bash
1. Go to 'Pickers' and click on 'Add New Picker'.
2. Trigger the error messages to show up and check the position of the [Cancel] and [Confirm] buttons. They change according to the form length, rather than sticking to the bottom.
```

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by ReinhardtBotha** [comment]
fixed
