### ISSUE TITLE
[Bug]: Picker - Add Picker - Drawer Title Font Size

### ISSUE THREAD

**Issue by Lizetteffkb** [LangaraVoyagers/project-2#41]
### Description

Font size for title in drawer should be 36px [Display/md/SemiBold]

### Reproduction steps

```bash
1. Go to 'Pickers' page and click on 'Add New Picker'
2. Open inspector and check the font size of the title 'Add Picker', it is in 48px while it should be in 36px.
```

### Screenshots / Screen Recordings

Png on Google Drive [https://drive.google.com/file/d/1pqPYURfaOaKyAzyqdVA_-Rl_FUuqHWG4/view?usp=sharing](url)
File name: drawer-title-font-size.png

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by ReinhardtBotha** [comment]
fixed
