### ISSUE TITLE
[Bug]: Picker - Drawer Input Label in Wrong Font Weight

### ISSUE THREAD

**Issue by Lizetteffkb** [LangaraVoyagers/project-2#43]
### Description

The font weight for the input label should be Medium (500), corresponding to [Text/md/Medium] in the font sheet.

Font sheet [https://www.figma.com/file/EGpc9IrOeCK3xmIxYWmhcQ/Mock-Up?type=design&node-id=474-18766&mode=design](url)

### Reproduction steps

```bash
1. Go to 'Pickers' page and click on 'Add New Picker'
2. Open inspector and check the font info of input label, it is 400 while it should be 500.
```

### Screenshots / Screen Recordings

![Screenshot 2024-03-14 at 6 56 41 PM](https://github.com/LangaraVoyagers/project-2/assets/114675207/f9052bfc-33cb-4fa2-8ae3-11c304b96e1f)

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by ReinhardtBotha** [comment]
fixed
