### ISSUE TITLE
Harvest Log Form Validation - Input field error messages need to be fixed

### ISSUE THREAD

**Issue by poojachauhan001** [LangaraVoyagers/project-2#65]
### Description

When some compulsory fields are left empty, the error messages speak the language of devs. We need to have simplified error message that are easy to be understood by users.

### Reproduction steps

```bash
1. go to ‘harvest log’ page
2. click on ‘add new log’
3. fill some info
4. leave an input field empty
5. click on ‘save’
```

### Screenshots / Screen Recordings

<img width="1440" alt="harvest-log-form" src="https://github.com/LangaraVoyagers/project-2/assets/144421139/645a58a2-a2eb-4b79-85cc-2b971293ce70">

### Browsers

Chrome

### OS

Mac

**Comment by ReinhardtBotha** [comment]
we need to put custom error messages for all the validation
