### ISSUE TITLE
Harvest Log - Amount should not display as negative

### ISSUE THREAD

**Issue by YaniceJ** [LangaraVoyagers/project-2#75]
### Description

When creating or editing a harvest log, the amount should not be able to display negative numbers

### Reproduction steps

```bash
1. Go to 'Harvest Log Page'
2. Click on 'Add New Log'
3. Scroll down to 'Amount'
4. Input or Click on the spin button next to the amount
4. See error
```

### Screenshots / Screen Recordings

Paste, drag and drop, or click option below to add your files here.
![Harvest Log - Amount should not display as negative](https://github.com/LangaraVoyagers/project-2/assets/161170980/dde3214d-cebb-4e7d-8e68-c11f1eb6e0b7)

### Browsers

Chrome

### OS

Mac

**Comment by whamester** [comment]
The harvest log can have negative amounts.
